import Nails4 from '../Assets/Nails 4.jpg'


const data = [
    {
        id: 1,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 2,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant ",
      },

      {
        id: 3,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant ",
      },{
        id: 4,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 5,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant ",
      },
      {
        id: 6,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 7,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 8,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 9,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 10,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 11,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 12,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Nails",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 13,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 14,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 15,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 16,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 17,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 18,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 19,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to",
      },
      {
        id: 20,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 21,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
      {
        id: 22,
        image: Nails4 ,
        title: "Versatile Website",
        category: "Hair",
        price: 150,
        desc: "This is a website that is meant to ",
      },
]
export default data